title       = "hupu"
baseURL     = "https://hupu-cli-cli.tamnd.com/"
description = "Browse Hupu sports community posts (虎扑)"
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/hupu-cli-cli"
